language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source --dev

before_script:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - phpunit --coverage-clover tests/coverage-clover.xml

after_script:
  - bin/aftertest
